use std::{env,fs::File,io::{self,Read,Write}};
const I:usize=784;const H:usize=128;const O:usize=10;
struct R(u64);impl R{fn n(&mut self)->u64{self.0^=self.0<<7;self.0^=self.0>>9;self.0}fn f(&mut self)->f32{((self.n()>>40)as f32/16777216.0)-0.5}fn u(&mut self,n:usize)->usize{self.n()as usize%n}}
struct M{w1:Vec<f32>,b1:Vec<f32>,w2:Vec<f32>,b2:Vec<f32>}
fn new()->M{let mut r=R(17);let mut w1=vec![0.0;I*H];let mut w2=vec![0.0;H*O];for x in &mut w1{*x=r.f()*0.08}for x in &mut w2{*x=r.f()*0.12}M{w1,b1:vec![0.0;H],w2,b2:vec![0.0;O]}}
fn idx(path:&str,labels:bool)->io::Result<(Vec<Vec<f32>>,Vec<u8>)>{let mut b=Vec::new();File::open(path)?.read_to_end(&mut b)?;let start=if labels{8}else{16};let n=if labels{u32::from_be_bytes([b[4],b[5],b[6],b[7]])as usize}else{u32::from_be_bytes([b[4],b[5],b[6],b[7]])as usize};if labels{Ok((vec![vec![];n],b[start..start+n].to_vec()))}else{let mut xs=Vec::with_capacity(n);for s in 0..n{let o=start+s*I;xs.push(b[o..o+I].iter().map(|&v|v as f32/255.).collect())}Ok((xs,vec![]))}}
fn run(m:&M,x:&[f32],z:&mut[f32;H],p:&mut[f32;O]){for j in 0..H{let mut v=m.b1[j];for i in 0..I{v+=m.w1[j*I+i]*x[i]}z[j]=v.max(0.)}let mut mx=-1e9;for k in 0..O{let mut v=m.b2[k];for j in 0..H{v+=m.w2[k*H+j]*z[j]}p[k]=v;if v>mx{mx=v}}let mut s=0.0;for k in 0..O{p[k]=(p[k]-mx).exp();s+=p[k]}for v in p.iter_mut(){*v/=s}}
fn main()->io::Result<()>{let a:Vec<String>=env::args().collect();if a.len()<4{println!("train <images> <labels> <model> [epochs]\neval <model> <images> <labels>");return Ok(())}let train=a[1]=="train";let (xs,ys)=(if train{let(x,_)=idx(&a[2],false)?;let(_,y)=idx(&a[3],true)?;(x,y)}else{let(x,_)=idx(&a[3],false)?;let(_,y)=idx(&a[4],true)?;(x,y)});let mut m=if train{if std::path::Path::new(&a[4]).exists(){let mut f=File::open(&a[4])?;let mut b=Vec::new();f.read_to_end(&mut b)?;let mut q=0;let mut t=|n:usize|{let mut v=Vec::with_capacity(n);for _ in 0..n{v.push(f32::from_le_bytes([b[q],b[q+1],b[q+2],b[q+3]]));q+=4}v};M{w1:t(I*H),b1:t(H),w2:t(H*O),b2:t(O)}}else{new()}}else{let mut f=File::open(&a[2])?;let mut b=Vec::new();f.read_to_end(&mut b)?;let mut q=0;let mut t=|n:usize|{let mut v=Vec::with_capacity(n);for _ in 0..n{v.push(f32::from_le_bytes([b[q],b[q+1],b[q+2],b[q+3]]));q+=4}v};M{w1:t(I*H),b1:t(H),w2:t(H*O),b2:t(O)}};let mut z=[0.0;H];let mut p=[0.0;O];if train{let ep=a.get(5).and_then(|v|v.parse().ok()).unwrap_or(8);let mut ord:(Vec<usize>)=(0..xs.len()).collect();let mut r=R(9);for e in 0..ep{for i in (1..ord.len()).rev(){let j=r.u(i+1);ord.swap(i,j)}let mut ok=0;let mut loss=0.0;for&s in &ord{run(&m,&xs[s],&mut z,&mut p);let y=ys[s]as usize;loss-=p[y].max(1e-9).ln();let k=(0..O).max_by(|&a,&b|p[a].total_cmp(&p[b])).unwrap();if k==y{ok+=1}let mut dz=[0.0;H];for k in 0..O{let g=p[k]-(k==y)as i32 as f32;for j in 0..H{dz[j]+=g*m.w2[k*H+j];m.w2[k*H+j]-=0.03*g*z[j]}m.b2[k]-=0.03*g}for j in 0..H{if z[j]>0.0{for i in 0..I{m.w1[j*I+i]-=0.03*dz[j].clamp(-2.0,2.0)*xs[s][i]}m.b1[j]-=0.03*dz[j].clamp(-2.0,2.0)}}}println!("epoch {}/{} loss {:.4} accuracy {:.2}%",e+1,ep,loss/xs.len()as f32,100.*ok as f32/xs.len()as f32)}let mut f=File::create(&a[4])?;for v in m.w1.iter().chain(m.b1.iter()).chain(m.w2.iter()).chain(m.b2.iter()){f.write_all(&v.to_le_bytes())?}}
let mut ok=0;for(s,x)in xs.iter().enumerate(){run(&m,x,&mut z,&mut p);let k=(0..O).max_by(|&a,&b|p[a].total_cmp(&p[b])).unwrap();if k==ys[s]as usize{ok+=1}}println!("evaluation accuracy {:.2}% ({}/{})",100.*ok as f32/xs.len()as f32,ok,xs.len());Ok(())}
