use std::{env,fs::File,io::{self,Read,Write}};
const Z:usize=16;const C:usize=10;const IN:usize=Z+C;const H:usize=128;const OUT:usize=784;
struct R(u64);impl R{fn n(&mut self)->u64{self.0^=self.0<<7;self.0^=self.0>>9;self.0}fn f(&mut self)->f32{((self.n()>>40)as f32/16777216.0)-0.5}}
struct G{w1:Vec<f32>,b1:Vec<f32>,w2:Vec<f32>,b2:Vec<f32>}
fn new()->G{let mut r=R(3);let mut w1=vec![0.0;IN*H];let mut w2=vec![0.0;H*OUT];for v in &mut w1{*v=r.f()*0.08}for v in &mut w2{*v=r.f()*0.08}G{w1,b1:vec![0.0;H],w2,b2:vec![0.0;OUT]}}
fn read_images(p:&str,labels:&str,limit:usize)->io::Result<(Vec<Vec<f32>>,Vec<u8>)>{let mut ib=Vec::new();let mut lb=Vec::new();File::open(p)?.read_to_end(&mut ib)?;File::open(labels)?.read_to_end(&mut lb)?;let n=(u32::from_be_bytes([lb[4],lb[5],lb[6],lb[7]])as usize).min(limit);let mut xs=Vec::with_capacity(n);let mut ys=Vec::with_capacity(n);for s in 0..n{let o=16+s*OUT;xs.push(ib[o..o+OUT].iter().map(|&v|v as f32/255.).collect());ys.push(lb[8+s])}Ok((xs,ys))}
fn sig(x:f32)->f32{1.0/(1.0+(-x).exp())}
fn forward(g:&G,x:&[f32],z:&mut[f32;H],y:&mut[f32;OUT]){for j in 0..H{let mut v=g.b1[j];for i in 0..IN{v+=g.w1[j*IN+i]*x[i]}z[j]=v.max(0.0)}for p in 0..OUT{let mut v=g.b2[p];for j in 0..H{v+=g.w2[p*H+j]*z[j]}y[p]=sig(v)}}
fn save(g:&G,p:&str)->io::Result<()>{let mut f=File::create(p)?;f.write_all(b"GEN1")?;for v in g.w1.iter().chain(g.b1.iter()).chain(g.w2.iter()).chain(g.b2.iter()){f.write_all(&v.to_le_bytes())?}Ok(())}
fn load(p:&str)->io::Result<G>{let mut b=Vec::new();File::open(p)?.read_to_end(&mut b)?;let mut q=4;let mut t=|n:usize|{let mut v=Vec::with_capacity(n);for _ in 0..n{v.push(f32::from_le_bytes([b[q],b[q+1],b[q+2],b[q+3]]));q+=4}v};Ok(G{w1:t(IN*H),b1:t(H),w2:t(H*OUT),b2:t(OUT)})}
fn train(mut g:G,xs:&[Vec<f32>],ys:&[u8],epochs:usize,out:&str)->io::Result<()>{let mut r=R(77);let lr=0.01;let mut z=[0.0;H];let mut y=[0.0;OUT];let mut x=[0.0;IN];for e in 0..epochs{let mut loss=0.0;for s in 0..xs.len(){for i in 0..Z{x[i]=r.f()}for i in 0..C{x[Z+i]=(i as u8==ys[s])as i32 as f32}forward(&g,&x,&mut z,&mut y);for p in 0..OUT{let t=xs[s][p];loss+=-(t*y[p].max(1e-6).ln()+(1.-t)*(1.-y[p]).max(1e-6).ln());}let mut dz=[0.0;H];for p in 0..OUT{let dy=y[p]-xs[s][p];for j in 0..H{dz[j]+=dy*g.w2[p*H+j];g.w2[p*H+j]-=lr*dy*z[j]}g.b2[p]-=lr*dy}for j in 0..H{if z[j]>0.{for i in 0..IN{g.w1[j*IN+i]-=lr*dz[j]*x[i]}g.b1[j]-=lr*dz[j]}}}println!("epoch {}/{} BCE {:.5}",e+1,epochs,loss/(xs.len()*OUT)as f32)}save(&g,out)}
fn generate(g:&G,class:usize,out:&str,seed:u64)->io::Result<()>{let mut r=R(seed);let mut x=[0.0;IN];for i in 0..Z{x[i]=r.f()}x[Z+class]=1.;let mut z=[0.0;H];let mut y=[0.0;OUT];forward(g,&x,&mut z,&mut y);let mut f=File::create(out)?;writeln!(f,"P5\n28 28\n255")?;for v in y{f.write_all(&[(v*255.)as u8])?}println!("generated class={} output={}",class,out);Ok(())}
fn main()->io::Result<()>{let a:Vec<String>=env::args().collect();match a.get(1).map(String::as_str){Some("train")=>{let lim=a.get(5).and_then(|v|v.parse().ok()).unwrap_or(10000);let(x,y)=read_images(&a[2],&a[3],lim)?;train(new(),&x,&y,a.get(6).and_then(|v|v.parse().ok()).unwrap_or(3),&a[4])},Some("generate")=>generate(&load(&a[2])?,a[3].parse().unwrap(),&a[4],a.get(5).and_then(|v|v.parse().ok()).unwrap_or(1)),_=>{println!("train <images> <labels> <model.tlm> [unused] [limit] [epochs]\ngenerate <model.tlm> <class 0-9> <out.pgm> [seed]");Ok(())}}}
